# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev_practice',
                'doc_host': 'https://eder-miguel.github.io',
                'git_url': 'https://github.com/eder-miguel/nbdev_practice',
                'lib_path': 'nbdev_practice'},
  'syms': {'nbdev_practice.core': {'nbdev_practice.core.foo': ('core.html#foo', 'nbdev_practice/core.py')}}}
